Vagrant.configure(2) do |config|
  config.vm.box = 'windows-server-core-1709'

  config.vm.hostname = 'example'

  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.provider 'libvirt' do |lv|
    lv.memory = 2048
    lv.cpus = 2
    lv.keymap = 'pt'
    lv.nested = true
    lv.cpu_mode = "host-model"
    config.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 2048
    vb.cpus = 2
  end
end
