Vagrant.configure(2) do |config|
  config.vm.box = 'windows-server-core-1709'

  config.vm.hostname = 'example'

  config.vm.provider 'libvirt' do |lv|
    lv.memory = 2048
    lv.cpus = 2
    lv.keymap = 'pt'
    config.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 2048
    vb.cpus = 2
  end
end
